version: '3.1'

services:  
  db:
    # build: Backend/database
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - ./Backend/database/sql:/docker-entrypoint-initdb.d
      - ./Backend/database/database.sql:/test.sql

  backend:
    build: Backend/scala-backend
    depends_on: 
      - db
    ports: 
      - "9000:9000"
    volumes:
      - ./Backend/scala-backend/app:/src/app
      - ./Backend/scala-backend/conf:/src/conf
