version: '3.4'

services:  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - ./Backend/database/sql:/docker-entrypoint-initdb.d
      - ./Backend/database/database:/var/lib/postgresql/data

  backend:
    build: 
      context: Backend/scala-backend
      target: dev
    depends_on: 
      - db
    ports: 
      - "9000:9000"
    volumes:
      - ./Backend/scala-backend/app:/src/app
      - ./Backend/scala-backend/conf:/src/conf
  frontend:
    build: klassentrenner-ui
    ports:
    - "80:80"
    # volumes:
    #   - ./klassentrenner-ui/:/app
