version: '3.1'

services:  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - $HOME/Desktop/postgres-Snippets/test.sql:/test.sql
    network_mode: bridge 